package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.Menu;
import com.benxiaopao.provider.dao.model.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @SelectProvider(type=MenuSqlProvider.class, method="countByExample")
    long countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @DeleteProvider(type=MenuSqlProvider.class, method="deleteByExample")
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @Delete({
        "delete from menu",
        "where menuId = #{menuId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @Insert({
        "insert into menu (menuId, parentId, ",
        "menuName, showOrder, ",
        "url, isVisible)",
        "values (#{menuId,jdbcType=INTEGER}, #{parentId,jdbcType=INTEGER}, ",
        "#{menuName,jdbcType=VARCHAR}, #{showOrder,jdbcType=INTEGER}, ",
        "#{url,jdbcType=VARCHAR}, #{isVisible,jdbcType=TINYINT})"
    })
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @InsertProvider(type=MenuSqlProvider.class, method="insertSelective")
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @SelectProvider(type=MenuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="menuId", property="menuId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="parentId", property="parentId", jdbcType=JdbcType.INTEGER),
        @Result(column="menuName", property="menuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="showOrder", property="showOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="isVisible", property="isVisible", jdbcType=JdbcType.TINYINT)
    })
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @Select({
        "select",
        "menuId, parentId, menuName, showOrder, url, isVisible",
        "from menu",
        "where menuId = #{menuId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="menuId", property="menuId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="parentId", property="parentId", jdbcType=JdbcType.INTEGER),
        @Result(column="menuName", property="menuName", jdbcType=JdbcType.VARCHAR),
        @Result(column="showOrder", property="showOrder", jdbcType=JdbcType.INTEGER),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="isVisible", property="isVisible", jdbcType=JdbcType.TINYINT)
    })
    Menu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @UpdateProvider(type=MenuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @UpdateProvider(type=MenuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @UpdateProvider(type=MenuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    @Update({
        "update menu",
        "set parentId = #{parentId,jdbcType=INTEGER},",
          "menuName = #{menuName,jdbcType=VARCHAR},",
          "showOrder = #{showOrder,jdbcType=INTEGER},",
          "url = #{url,jdbcType=VARCHAR},",
          "isVisible = #{isVisible,jdbcType=TINYINT}",
        "where menuId = #{menuId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Menu record);
}