package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.Menu;
import com.benxiaopao.provider.dao.model.MenuExample.Criteria;
import com.benxiaopao.provider.dao.model.MenuExample.Criterion;
import com.benxiaopao.provider.dao.model.MenuExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MenuSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    public String countByExample(MenuExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("menu");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    public String deleteByExample(MenuExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("menu");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    public String insertSelective(Menu record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("menu");
        
        if (record.getMenuId() != null) {
            sql.VALUES("menuId", "#{menuId,jdbcType=INTEGER}");
        }
        
        if (record.getParentId() != null) {
            sql.VALUES("parentId", "#{parentId,jdbcType=INTEGER}");
        }
        
        if (record.getMenuName() != null) {
            sql.VALUES("menuName", "#{menuName,jdbcType=VARCHAR}");
        }
        
        if (record.getShowOrder() != null) {
            sql.VALUES("showOrder", "#{showOrder,jdbcType=INTEGER}");
        }
        
        if (record.getUrl() != null) {
            sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getIsVisible() != null) {
            sql.VALUES("isVisible", "#{isVisible,jdbcType=TINYINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    public String selectByExample(MenuExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("menuId");
        } else {
            sql.SELECT("menuId");
        }
        sql.SELECT("parentId");
        sql.SELECT("menuName");
        sql.SELECT("showOrder");
        sql.SELECT("url");
        sql.SELECT("isVisible");
        sql.FROM("menu");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Menu record = (Menu) parameter.get("record");
        MenuExample example = (MenuExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("menu");
        
        if (record.getMenuId() != null) {
            sql.SET("menuId = #{record.menuId,jdbcType=INTEGER}");
        }
        
        if (record.getParentId() != null) {
            sql.SET("parentId = #{record.parentId,jdbcType=INTEGER}");
        }
        
        if (record.getMenuName() != null) {
            sql.SET("menuName = #{record.menuName,jdbcType=VARCHAR}");
        }
        
        if (record.getShowOrder() != null) {
            sql.SET("showOrder = #{record.showOrder,jdbcType=INTEGER}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        }
        
        if (record.getIsVisible() != null) {
            sql.SET("isVisible = #{record.isVisible,jdbcType=TINYINT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("menu");
        
        sql.SET("menuId = #{record.menuId,jdbcType=INTEGER}");
        sql.SET("parentId = #{record.parentId,jdbcType=INTEGER}");
        sql.SET("menuName = #{record.menuName,jdbcType=VARCHAR}");
        sql.SET("showOrder = #{record.showOrder,jdbcType=INTEGER}");
        sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        sql.SET("isVisible = #{record.isVisible,jdbcType=TINYINT}");
        
        MenuExample example = (MenuExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    public String updateByPrimaryKeySelective(Menu record) {
        SQL sql = new SQL();
        sql.UPDATE("menu");
        
        if (record.getParentId() != null) {
            sql.SET("parentId = #{parentId,jdbcType=INTEGER}");
        }
        
        if (record.getMenuName() != null) {
            sql.SET("menuName = #{menuName,jdbcType=VARCHAR}");
        }
        
        if (record.getShowOrder() != null) {
            sql.SET("showOrder = #{showOrder,jdbcType=INTEGER}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getIsVisible() != null) {
            sql.SET("isVisible = #{isVisible,jdbcType=TINYINT}");
        }
        
        sql.WHERE("menuId = #{menuId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Wed Apr 03 23:31:44 CST 2019
     */
    protected void applyWhere(SQL sql, MenuExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}