package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.RoleMenuPurviewExample;
import com.benxiaopao.provider.dao.model.RoleMenuPurviewKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RoleMenuPurviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @SelectProvider(type=RoleMenuPurviewSqlProvider.class, method="countByExample")
    long countByExample(RoleMenuPurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @DeleteProvider(type=RoleMenuPurviewSqlProvider.class, method="deleteByExample")
    int deleteByExample(RoleMenuPurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @Delete({
        "delete from role_menu_purview",
        "where roleId = #{roleId,jdbcType=INTEGER}",
          "and menuId = #{menuId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(RoleMenuPurviewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @Insert({
        "insert into role_menu_purview (roleId, menuId)",
        "values (#{roleId,jdbcType=INTEGER}, #{menuId,jdbcType=INTEGER})"
    })
    int insert(RoleMenuPurviewKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @InsertProvider(type=RoleMenuPurviewSqlProvider.class, method="insertSelective")
    int insertSelective(RoleMenuPurviewKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @SelectProvider(type=RoleMenuPurviewSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="roleId", property="roleId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menuId", property="menuId", jdbcType=JdbcType.INTEGER, id=true)
    })
    List<RoleMenuPurviewKey> selectByExample(RoleMenuPurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @UpdateProvider(type=RoleMenuPurviewSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RoleMenuPurviewKey record, @Param("example") RoleMenuPurviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_purview
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    @UpdateProvider(type=RoleMenuPurviewSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RoleMenuPurviewKey record, @Param("example") RoleMenuPurviewExample example);
}