package com.benxiaopao.provider.dao.model;

public class RoleMenuPurviewKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_purview.roleId
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_purview.menuId
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_purview.roleId
     *
     * @return the value of role_menu_purview.roleId
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_purview.roleId
     *
     * @param roleId the value for role_menu_purview.roleId
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_purview.menuId
     *
     * @return the value of role_menu_purview.menuId
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_purview.menuId
     *
     * @param menuId the value for role_menu_purview.menuId
     *
     * @mbg.generated Wed Apr 03 23:32:12 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}